collision_spheres:
  dual_rm_75b_description_platform_base_link:
  - center:
    - 0.0
    - 0.0
    - 0.1
    radius: 0.03
  - center:
    - 0.1
    - 0.0
    - 0.1
    radius: 0.03
  - center:
    - -0.1
    - 0.0
    - 0.1
    radius: 0.03
  dual_rm_75b_description_r_link1:
  - center:
    - 0.0
    - 0.0
    - -0.15000000000000002
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - -0.05
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - 0.05
    radius: 0.06
  dual_rm_75b_description_r_link2:
  - center:
    - 0.0
    - 0.0
    - -0.15000000000000002
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - -0.05
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - 0.05
    radius: 0.06
  dual_rm_75b_description_r_link3:
  - center:
    - 0.0
    - 0.0
    - -0.15000000000000002
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - -0.05
    radius: 0.06
  - center:
    - 0.0
    - 0.0
    - 0.05
    radius: 0.06
  dual_rm_75b_description_r_link4:
  - center:
    - 0.0
    - 0.0
    - -0.2
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.1
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.1
    radius: 0.05
  dual_rm_75b_description_r_link5:
  - center:
    - 0.0
    - 0.0
    - -0.2
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.1
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.1
    radius: 0.05
  dual_rm_75b_description_r_link6:
  - center:
    - 0.0
    - 0.0
    - -0.2
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.1
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.1
    radius: 0.05
  r_link7:
  - center:
    - 0.0
    - 0.0
    - -0.2
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - -0.1
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.05
  - center:
    - 0.0
    - 0.0
    - 0.1
    radius: 0.05
  panda_right_hand:
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.04
  - center:
    - 0.05
    - 0.0
    - 0.0
    radius: 0.04
  - center:
    - -0.05
    - 0.0
    - 0.0
    radius: 0.04
  - center:
    - 0.0
    - 0.0
    - 0.04
    radius: 0.025
  panda_right_leftfinger:
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.015
  - center:
    - 0.0
    - 0.02
    - 0.0
    radius: 0.012
  - center:
    - 0.0
    - 0.04
    - 0.0
    radius: 0.012
  panda_right_rightfinger:
  - center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.015
  - center:
    - 0.0
    - -0.02
    - 0.0
    radius: 0.012
  - center:
    - 0.0
    - -0.04
    - 0.0
    radius: 0.012
